        SET IDENTITY_INSERT [FIN阿米巴损益项] ON;

        -- 批次6: 一次性守卫重灌(§7.7) —— FID 600 缺失即清模板3并灌新 72 项
        IF NOT EXISTS (SELECT 1 FROM [FIN阿米巴损益项] WHERE [FID] = 600)
        BEGIN
            -- 仅清种子两段(旧414-495 + 新600-671), 不动用户运行期自定义项(其他FID)
            DELETE FROM [FIN阿米巴损益项] WHERE [F模板ID] = 3 AND ([FID] BETWEEN 414 AND 495 OR [FID] BETWEEN 600 AND 671);

            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (600, 3, N'出港', N'group', NULL, 10, 0, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (601, 3, N'出港指标', N'group', NULL, 10, 600, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (602, 3, N'发件票量', N'indicator', NULL, 10, 601, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'票', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (603, 3, N'发件重量', N'indicator', NULL, 20, 601, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'kg', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (604, 3, N'均重', N'indicator', NULL, 30, 601, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'kg/票', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (605, 3, N'计价件量', N'indicator', NULL, 40, 601, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'票', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (606, 3, N'揽件员人数', N'indicator', NULL, 50, 601, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'人', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (607, 3, N'揽件效能', N'indicator', NULL, 60, 601, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'件/人/日', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (608, 3, N'出港收入', N'group', NULL, 20, 600, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (609, 3, N'客户发件收入', N'group', NULL, 10, 608, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (610, 3, N'月结收入', N'data', NULL, 10, 609, N'[{"code": "50010102", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (611, 3, N'现付收入', N'data', NULL, 20, 609, N'[{"code": "50010101", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (612, 3, N'到付收入', N'data', NULL, 30, 609, N'[{"code": "50010103", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (613, 3, N'总部平台单', N'data', NULL, 40, 609, N'[{"code": "50010104", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (614, 3, N'政策返利', N'data', NULL, 20, 608, N'[{"code": "500105", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (615, 3, N'出港成本', N'group', NULL, 30, 600, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (616, 3, N'面单&派费', N'group', NULL, 10, 615, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (617, 3, N'面单', N'data', NULL, 10, 616, N'[{"code": "540101", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (618, 3, N'出港派费', N'data', NULL, 20, 616, N'[{"code": "540102", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (619, 3, N'中转费', N'group', NULL, 20, 615, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (620, 3, N'中转费', N'data', NULL, 10, 619, N'[{"code": "54010301", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (621, 3, N'全网出港费', N'data', NULL, 20, 619, N'[{"code": "54010304", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (622, 3, N'其他中转', N'data', NULL, 30, 619, N'[{"code": "54010302", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}, {"code": "54010303", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}, {"code": "54010305", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (623, 3, N'操作费', N'group', NULL, 30, 615, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (624, 3, N'集包费', N'data', NULL, 10, 623, N'[{"code": "54010401", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}, {"code": "54010402", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'send', N'科目余额', N'件量分摊(send);发件量为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (625, 3, N'操作费', N'data', NULL, 20, 623, N'[{"code": "54010403", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}, {"code": "54010404", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}, {"code": "54010405", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'send', N'科目余额', N'件量分摊(send);发件量为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (626, 3, N'运输费', N'data', NULL, 40, 615, N'[{"code": "540109", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (627, 3, N'物料费', N'data', NULL, 50, 615, N'[{"code": "540108", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (628, 3, N'增值服务费', N'data', NULL, 60, 615, N'[{"code": "540105", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (629, 3, N'考核罚款', N'data', NULL, 70, 615, N'[{"code": "540106", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (630, 3, N'客服理赔', N'data', NULL, 80, 615, N'[{"code": "540107", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (631, 3, N'揽件员工资', N'data', NULL, 90, 615, N'[{"code": "5601010101", "filters": [{"auxType": "department", "codes": ["YWY_OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (632, 3, N'出港操作工资', N'data', NULL, 100, 615, N'[{"code": "5601010103", "filters": [{"auxType": "business_direction", "codes": ["OUT"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'send', N'科目余额', N'件量分摊(send);发件量为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (633, 3, N'出港边际利润', N'formula', N'${出港收入} - ${出港成本}', 40, 600, NULL, NULL, N'formula', NULL, 0, N'profit', 0, N'元', N'none', NULL, NULL, NULL, NULL, N'${出港收入} - ${出港成本}', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (634, 3, N'进港', N'group', NULL, 20, 0, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (635, 3, N'进港指标', N'group', NULL, 10, 634, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (636, 3, N'派件票量', N'indicator', NULL, 10, 635, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'票', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (637, 3, N'派件重量', N'indicator', NULL, 20, 635, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'kg', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (638, 3, N'入库率', N'indicator', NULL, 30, 635, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'%', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (639, 3, N'派件员人数', N'indicator', NULL, 40, 635, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'人', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (640, 3, N'派件效能', N'indicator', NULL, 50, 635, NULL, NULL, N'manual', NULL, 1, N'indicator', 0, N'件/人/日', N'none', NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (641, 3, N'进港收入', N'group', NULL, 20, 634, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (642, 3, N'派费收入', N'group', NULL, 10, 641, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (643, 3, N'基础派费', N'data', NULL, 10, 642, N'[{"code": "50010201", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (644, 3, N'补贴派费', N'data', NULL, 20, 642, N'[{"code": "50010202", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (645, 3, N'考核派费', N'data', NULL, 30, 642, N'[{"code": "50010209", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (646, 3, N'其他派费', N'data', NULL, 40, 642, N'[{"code": "50010203", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}, {"code": "50010204", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}, {"code": "50010205", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}, {"code": "50010206", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}, {"code": "50010207", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}, {"code": "50010208", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}, {"code": "50010210", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}, {"code": "50010211", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (647, 3, N'考核激励', N'data', NULL, 20, 641, N'[{"code": "500106", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (648, 3, N'客服受款', N'data', NULL, 30, 641, N'[{"code": "500107", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (649, 3, N'其他收入(进港操作收入)', N'data', NULL, 40, 641, N'[{"code": "500103", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'revenue', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (650, 3, N'进港成本', N'group', NULL, 30, 634, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (651, 3, N'操作成本', N'data', NULL, 10, 650, N'[{"code": "540104", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (652, 3, N'派件成本', N'group', NULL, 20, 650, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (653, 3, N'承包区派费', N'data', NULL, 10, 652, N'[{"code": "54010211", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (654, 3, N'驿站费用', N'data', NULL, 20, 652, N'[{"code": "54010212", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (655, 3, N'运输成本', N'data', NULL, 30, 650, N'[{"code": "540109", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (656, 3, N'考核成本', N'data', NULL, 40, 650, N'[{"code": "540106", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (657, 3, N'赔付成本', N'data', NULL, 50, 650, N'[{"code": "540107", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (658, 3, N'物料成本', N'data', NULL, 60, 650, N'[{"code": "540108", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (659, 3, N'客服成本', N'data', NULL, 70, 650, N'[{"code": "5601010102", "filters": [{"auxType": "department", "codes": ["KF"]}]}, {"code": "560121", "filters": [{"auxType": "department", "codes": ["KF"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (660, 3, N'派件员工资', N'data', NULL, 80, 650, N'[{"code": "5601010101", "filters": [{"auxType": "department", "codes": ["YWY_IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, NULL, NULL, N'科目余额', N'直接归段', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (661, 3, N'进港操作工资', N'data', NULL, 90, 650, N'[{"code": "5601010103", "filters": [{"auxType": "business_direction", "codes": ["IN"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'deliver', N'科目余额', N'件量分摊(deliver);派件量为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (662, 3, N'进港边际利润', N'formula', N'${进港收入} - ${进港成本}', 40, 634, NULL, NULL, N'formula', NULL, 0, N'profit', 0, N'元', N'none', NULL, NULL, NULL, NULL, N'${进港收入} - ${进港成本}', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (663, 3, N'公共分摊', N'group', NULL, 30, 0, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (664, 3, N'房租/水电/折旧/摊销', N'group', NULL, 10, 663, NULL, NULL, NULL, NULL, 0, N'section', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (665, 3, N'房租', N'data', NULL, 10, 664, N'[{"code": "560104"}, {"code": "560204"}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'total', N'科目余额', N'件量分摊(total);为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (666, 3, N'水电', N'data', NULL, 20, 664, N'[{"code": "560105"}, {"code": "560205"}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'total', N'科目余额', N'件量分摊(total);为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (667, 3, N'折旧', N'data', NULL, 30, 664, N'[{"code": "560102"}, {"code": "560202"}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'total', N'科目余额', N'件量分摊(total);为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (668, 3, N'摊销', N'data', NULL, 40, 664, N'[{"code": "560103"}, {"code": "560203"}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'total', N'科目余额', N'件量分摊(total);为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (669, 3, N'管理费用', N'data', NULL, 20, 663, N'[{"code": "560206"}, {"code": "560207"}, {"code": "560208"}, {"code": "56020901"}, {"code": "56020902"}, {"code": "560210"}, {"code": "560211"}, {"code": "560212"}, {"code": "560213"}, {"code": "560214"}, {"code": "560215"}, {"code": "560216"}, {"code": "560217"}, {"code": "560218"}, {"code": "560219"}, {"code": "560220"}, {"code": "560221"}, {"code": "560222"}, {"code": "560223"}, {"code": "560299"}, {"code": "5601010105", "filters": [{"auxType": "department", "codes": ["YWGL"]}]}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'total', N'科目余额', N'件量分摊(total);为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (670, 3, N'财务费用', N'data', NULL, 30, 663, N'[{"code": "5603"}]', NULL, N'system', N'voucher', 0, N'cost', 0, N'元', N'auto', NULL, N'volume', N'total', N'科目余额', N'件量分摊(total);为单票基数', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
            INSERT INTO [FIN阿米巴损益项] ([FID], [F模板ID], [F项目名称], [F节点角色], [F计算公式], [F排序], [F父ID], [F关联科目JSON], [F计费过滤Json], [F值来源], [F系统数据源], [F是否手工填报], [F项目类别], [F是否指标分区], [F单位], [F单票均模式], [F小数位数], [F分摊方式], [F分摊基数], [F数据来源说明], [F计算逻辑], [F创建时间], [F更新时间]) VALUES (671, 3, N'经营净利润', N'formula', N'${出港边际利润} + ${进港边际利润} - ${公共分摊}', 40, 0, NULL, NULL, N'formula', NULL, 0, N'profit', 0, N'元', N'none', NULL, NULL, NULL, NULL, N'${出港边际利润} + ${进港边际利润} - ${公共分摊}', N'2026-06-17 00:00:00.000', N'2026-06-17 00:00:00.000');
        END

        SET IDENTITY_INSERT [FIN阿米巴损益项] OFF;
